### ISSUE TITLE
[RA2] Align with RM v5

### ISSUE THREAD

**Issue by rgstori** [anuket-project/anuket-specifications#2285]
Placeholder for discussion - to be broken down in sub-issues

Delta from v4 (baraque) to v5 (elbrus):

[chapter 3 - modeling](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md):
3.3 - added content under VIM / HIM
3.4.1 - added Hardware Acceleration Resources - introduction to chapter 3.8
3.5 - networking fleshed out
3.5.1 - added Service Function Chaining - Issue #2276 has been opened by @kumarsumangit to update 
3.6 - storage unchanged
3.7 - sample reference model realisation - unchanged
3.8 - new chapter: Hardware Acceleration Abstraction

[chapter 4](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter04.md) - terminology, couple paragraphs added (on overlay network and ephermeral disk)

chapter 5,6 - typos

[chapter 7](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter07.md) - added req.sec.sys.015 to req.sec.sys.019

[chapter 8](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter08.md) - new chapter Hybrid Multi-Cloud: Data Center to Edge, incl. multi-cloud, telco edge cloud

[chapter 9](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter09.md) - added 9.5 and 9.6 telemetry observability  automation

[chapter 10](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter10.md) - added 10.3.6 Closed-loop automation

**Comment by pgoyal01** [comment]
@rgstori Please note that RM Issue #2276 has been opened by @kumarsumangit to update the RM 3.5.1 - Service Function Chaining section.

**Comment by rgstori** [comment]
sure, let me track it in the original comment, thanks

**Comment by petorre** [comment]
On HW Acceleration (RM 3.4.1 Hardware Acceleration Resources, and 3.8 Hardware Acceleration Abstraction) some alignment is already in 3.2.1.6 Device Plugin Framework, 3.2.1.7 Hardware Acceleration and 3.2.1.8 Scheduling Pods with Non-resilient Applications. To describe some more we have issue #2255 .
