### ISSUE TITLE
[RA2 Ch3] Add Smart Switches

### ISSUE THREAD

**Issue by petorre** [anuket-project/anuket-specifications#2330]
Describe how [Smart Switches](https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter03.md#3.8.8) fit in RA2 \ [High Level Architecture.](https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/chapters/chapter03.md)

**Comment by rgstori** [comment]
could be generalised - management of images and configuration of DC network devices
