### ISSUE TITLE
[RA2 Ch4] Specs for caas manager interface - CaaS LCM IaC

### ISSUE THREAD

**Issue by rgstori** [anuket-project/anuket-specifications#2792]
from D&T forum jan 22

`Multitenancy - Ulrich Kleber highlights Hard Multitenancy implies CaaS Cluster LCM should be in scope - need at least to specify the interface to CaaS manager, like IFA 036, avoiding cloud-specific implementation specs `

**Comment by TFredberg** [comment]
Have you looked into O-RAN WG6?
They today work under the assumption that regular K8s interfaces will be used for managing workload placement in/on K8s Clusters and by that they will not stop/delay the continuous innovation that happens in that space, through standardization that will only limit what can be done. That imply that the management systems will have to have suitable management plug-ins to handle each specific CaaS from these aspects. This type of K8s management is call Deployment Management Services (DMS).
They also have a Provisioning interface that requests K8s Clusters to be Provisioned from the O-Cloud Infrastructure Management Services (IMS). This IMS interface abstracts any differences of what K8s Cluster to create, initialize and scale (as a cluster).
These interfaces are not ready and released, but the description above shows their intent.

**Comment by rgstori** [comment]
to split in sub-issues about CaaS Manager northbound interfaces
support of LCM operations
support of node flavours in the API - including VM/BM

**Comment by rgstori** [comment]
@TFredberg thanks for this, do you mind working with Uli and adding any details on the O2 interface requirements here, please?

**Comment by rgstori** [comment]
This must be mapped onto the Automation - IaC section of RM #2087
