### ISSUE TITLE
[ra2 ch4] check host os requirement compatibility with recent k8s versions

### ISSUE THREAD

**Issue by rgstori** [anuket-project/anuket-specifications#2974]
eg **Table 4-3:** Operating System Versions

**Comment by rgstori** [comment]
host os requirements generated from:

- k8s itself (kernel version, swap being disabled)
-  container runtime driven requirements
- ra2 features (cpu sizing, multiple network interfaces...)

**Comment by petorre** [comment]
Will this also get closed with very complete #3351 ?
