### ISSUE TITLE
[RM Ch8/Ch9] 6G Requirements & Architecture

### ISSUE THREAD

**Issue by joaoarodrigues** [anuket-project/anuket-specifications#3214]
Anuket shall take in consideration the support of 6G Technology by evolving the Reference Model in order to cope with strict requirements brought by new use cases. Take in consideration the following capabilities:

- Extreme Edge Support
- Continuum Orchestration
- Cloud Infrastructure Convergenge
- Network Programability 

Its necessary to update the following chapters according to the above points:

- [Chapter 8](https://cntt.readthedocs.io/projects/rm/en/stable-moselle/chapters/chapter08.html)
- [Chapter 9](https://cntt.readthedocs.io/projects/rm/en/stable-moselle/chapters/chapter09.html)

Use cases shall be included in:

- [Chapter 2](https://cntt.readthedocs.io/projects/rm/en/stable-moselle/chapters/chapter02.html)

**Comment by joaoarodrigues** [comment]
The list below provides a guidance on the 6G use cases that may exist, those are grouped in five family use casesuse cases (aligned to Hexa-X research project). Its clearly expected the list can be expanded due to the availability of new requirements brought by  use cases.

**- Sustainable Development:** E-health for all; Earth Monitor; Autonomous Supply Chains

**- Massive Twinning:** Immersive Smart City; Digital Twins for manufacturing

**- Telepresence:** Mixed reality co-design; Immersive sport event; Merged reality game/work

**- Robots to robots:** Consumer robots; Interacting and cooperative mobile robots

**- Local Trust Zones:** Precision healthcare, Sensor infrastructure web; Infrastructure-less network extensions and embedded networks; small coverage, low power micro-network in networks for production & manufacturing

**Comment by pgoyal01** [comment]
@joaoarodrigues 6G Use case should be added to Chapter 2. One question that needs to be addressed is why these use cases need the 6G level extremely high-speed networking.

**Comment by joaoarodrigues** [comment]
@pgoyal01 I've now included a reference to chapter 2.

Its about latency which needs to be managed, for instance a user in a VR use case, experiences dizziness and connection instability due to the need to hold and wait for decisions that can be processed at the management plane. This is just an example but there are others related to the workload processing shall be executed as close as possible to the endpoint.

**Comment by joaoarodrigues** [comment]
It was completed with success:

- #3255 
- #3254 
- #3253
