### ISSUE TITLE
[RA2] Update K8s to v1.25

### ISSUE THREAD

**Issue by collivier** [anuket-project/anuket-specifications#3219]
As per Anuket rule, RA2 and RC2 must update its Kubernetes API and features to latest stable release before freeze.
RA2 is still in v1.23 which blocks RC2 and the agreed CNTT/Anuket rules 
(BYW v1.23 will be end of life 2023-02-28)

As mentioned in https://kubernetes.io/releases/, v1.23 was released 2022-09-21

**Comment by collivier** [comment]
FYI @bfcohen @walterkozlowski @pgoyal01 @karinesevilla

**Comment by rgstori** [comment]
propose to close as we have decided to stay on 1.24 for the N release - see
https://github.com/cntt-n/CNTT/issues/3085#issuecomment-1293688209
