### ISSUE TITLE
[RM Ch3] O-RAN alignment, O-Cloud requirements

### ISSUE THREAD

**Issue by petorre** [anuket-project/anuket-specifications#3297]
Overall alignment on Anuket implementing O-RAN cloud infra requirements, and O-RAN using Anuket specs.
Implement O-Cloud requirements like Monitoring (Notification Subscription) for HW resources (incl. master clock), or other in WG6 specs.

Co-assign @joaoarodrigues .

**Comment by ulikleber** [comment]
Sorry, I am not involved in O-RAN at all. I cannot take this assinged task.

**Comment by petorre** [comment]
(Just cleaning old issue) This issue got closed with #3371 .

**Comment by petorre** [comment]
Done
