### ISSUE TITLE
[Ra2] Update CNF workload tests

### ISSUE THREAD

**Issue by rgstori** [anuket-project/anuket-specifications#3312]
further align workload requirements with cncf wg based on current discussions
e.g. change some "must" reqs to "may"

**Comment by CsatariGergely** [comment]
I would propose the removal or clarification of some of the requirements: 

- ra2.app.001: It is not really clear what this requirement is and it is not tested in CNF Testbed
- ra2.app.002: It is not clear what is the requirement here. Is this about host mounts? This is not tested by CNF Testbed
- ra2.app.003: It is not clear what is the requirement here. This is not tested by CNF Testbed
- ra2.app.004: It is not clear what is the requirement here. Kubernetes sets the pod name by default. This is not tested by CNF Testbed
