### ISSUE TITLE
[RM Chxx] Updates to RM as an alignment to RA-2 Pieman

### ISSUE THREAD

**Issue by walterkozlowski** [anuket-project/anuket-specifications#3420]
The umbrella issue to cover for updates in RA-2 due to dynamic changes expected in RA-2 in Pieman release

**Comment by petorre** [comment]
Added load balanced, will add cert manager as per RA2[#7](https://github.com/anuket-project/RA2/pull/7).

**Comment by walterkozlowski** [comment]
PR#https://github.com/anuket-project/RM/pull/14 closes this issue for Pieman.  Another issue will be raised for the next release.

**Comment by walterkozlowski** [comment]
PR#https://github.com/anuket-project/RM/pull/14 closes this issue for Pieman. Another issue will be raised for the next release.
