### ISSUE TITLE
[RM Ch3 Ch7] Not rendering

### ISSUE THREAD

**Issue by petorre** [anuket-project/anuket-specifications#3427]
[RM Ch3](https://github.com/anuket-project/RM/blob/main/doc/ref_model/chapters/chapter03.rst) and [RM Ch7](https://github.com/anuket-project/RM/blob/main/doc/ref_model/chapters/chapter07.rst) don't render properly.

**Comment by walterkozlowski** [comment]
I can edit and assign now.

**Comment by petorre** [comment]
I looked into this.
In current RST format: For whatever reason it does not render properly. If I split it smaller files, those render fine - so it doesn't seem to be formatting problem.
[Converted](https://cloudconvert.com/rst-to-md) into MD format: Examples like [Ch3](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter07.md) and [Ch7](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter07.md) seem to render fine (but few URLs need to be corrected).

**Comment by walterkozlowski** [comment]
It must be the file size issue then. Perhaps we split up chapter 3 into
smaller chunks? Let’s discuss next week RM call

**Comment by petorre** [comment]
OK, will try to split it.

**Comment by petorre** [comment]
All still in RST format and renders well in my forked version:
Ch3 split into 4 files starting with [chapter03**a**.rst](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter03a.rst) , at the [end](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter03a.rst#continues) (so it comes also in Outline) has link to [next](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter03b.rst) which at the [beginning](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter03b.rst#modelling) has link to previous...
Ch7 split into 2 files starting with [chapter07**a**.rst](https://github.com/petorre/RM/blob/main/doc/ref_model/chapters/chapter07a.rst) with similar links.

Please check, let me know any guidance, and if I should do it on the main RM repo.

**Comment by petorre** [comment]
Something changed on the rendering engine, not on [RM Ch3](https://github.com/anuket-project/RM/blob/main/doc/ref_model/chapters/chapter03.rst) and [RM Ch7](https://github.com/anuket-project/RM/blob/main/doc/ref_model/chapters/chapter07.rst) which now again render properly.

**Comment by petorre** [comment]
It rendered during RM call on 27March2024 so we agreed to close this issue.
