### ISSUE TITLE
[RA2 Ch05] Secrets management

### ISSUE THREAD

**Issue by tomkivlin** [anuket-project/anuket-specifications#995]
From deep dive in Prague:
Secrets Mgmt
Do we really need to test for hardcoded passwords? (yes)
Is this for accessing the cluster or app-level?

**Comment by karinesevilla** [comment]
Rewrite Chapter 5 section 5.12 for secrets management to be more prescriptive

**Comment by karinesevilla** [comment]
Secrets Management section (5.12) has been expanded in chapter 5.
It addresses hard coded passwords:
"It is also important to implement the following:
Check there are no hard-coded passwords, keys, and other sensitive items in the container application.
Where possible use security tools to automate scanning for hard-coded passwords, keys, and other sensitive items in the container application"
@rgstori This issue can be closed
