### ISSUE TITLE
[RA2] Ch6 - SIEM standard interface

### ISSUE THREAD

**Issue by tomkivlin** [anuket-project/anuket-specifications#999]
From deep dive in Prague:
6.14
For SIEM - how to specify a standard interface? Start with stderr/stdout from each container, up to metrics-server, and so on until we find an issue (if we do) .

**Comment by karinesevilla** [comment]
@rgstori Rather than SIEM, RM requests the use of vulnerabilties scanner. 
Do we want to request as mandatory the integration with a SIEM system and specify the interface?
In my opinion, it is beyond our scope, and I think we can close this issue
